In [3]:
import torch



In [4]:

N_a = 6
N_b = 4
N_f = 10


In [5]:
f_ij = torch.rand(N_b, N_a, N_a-1, N_f)
nbh = torch.tensor([[[j for j in range(N_a) if j!=i] for i in range(N_a)] for _ in 
                    range(N_b)])
y = torch.rand(N_b, N_a, N_f)


In [6]:
f_ij.shape

torch.Size([4, 6, 5, 10])

In [7]:
nbh_shape = nbh.shape
nbh_shape


torch.Size([4, 6, 5])

In [8]:
nbh = nbh.view(nbh_shape[0], nbh_shape[1]*nbh_shape[2], 1)
nbh


tensor([[[1],
         [2],
         [3],
         [4],
         [5],
         [0],
         [2],
         [3],
         [4],
         [5],
         [0],
         [1],
         [3],
         [4],
         [5],
         [0],
         [1],
         [2],
         [4],
         [5],
         [0],
         [1],
         [2],
         [3],
         [5],
         [0],
         [1],
         [2],
         [3],
         [4]],

        [[1],
         [2],
         [3],
         [4],
         [5],
         [0],
         [2],
         [3],
         [4],
         [5],
         [0],
         [1],
         [3],
         [4],
         [5],
         [0],
         [1],
         [2],
         [4],
         [5],
         [0],
         [1],
         [2],
         [3],
         [5],
         [0],
         [1],
         [2],
         [3],
         [4]],

        [[1],
         [2],
         [3],
         [4],
         [5],
         [0],
         [2],
         [3],
         [4],
         [5],
         [0],
  

In [9]:
nbh = nbh.expand(-1, -1, N_f)
nbh.shape


torch.Size([4, 30, 10])

In [10]:
y.shape

torch.Size([4, 6, 10])

In [11]:
nbh

tensor([[[1, 1, 1,  ..., 1, 1, 1],
         [2, 2, 2,  ..., 2, 2, 2],
         [3, 3, 3,  ..., 3, 3, 3],
         ...,
         [2, 2, 2,  ..., 2, 2, 2],
         [3, 3, 3,  ..., 3, 3, 3],
         [4, 4, 4,  ..., 4, 4, 4]],

        [[1, 1, 1,  ..., 1, 1, 1],
         [2, 2, 2,  ..., 2, 2, 2],
         [3, 3, 3,  ..., 3, 3, 3],
         ...,
         [2, 2, 2,  ..., 2, 2, 2],
         [3, 3, 3,  ..., 3, 3, 3],
         [4, 4, 4,  ..., 4, 4, 4]],

        [[1, 1, 1,  ..., 1, 1, 1],
         [2, 2, 2,  ..., 2, 2, 2],
         [3, 3, 3,  ..., 3, 3, 3],
         ...,
         [2, 2, 2,  ..., 2, 2, 2],
         [3, 3, 3,  ..., 3, 3, 3],
         [4, 4, 4,  ..., 4, 4, 4]],

        [[1, 1, 1,  ..., 1, 1, 1],
         [2, 2, 2,  ..., 2, 2, 2],
         [3, 3, 3,  ..., 3, 3, 3],
         ...,
         [2, 2, 2,  ..., 2, 2, 2],
         [3, 3, 3,  ..., 3, 3, 3],
         [4, 4, 4,  ..., 4, 4, 4]]])

In [12]:


nbh[1]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],


In [13]:
y

tensor([[[0.9555, 0.0559, 0.4913, 0.8824, 0.0411, 0.6402, 0.5289, 0.3792,
          0.2099, 0.3326],
         [0.3855, 0.2628, 0.1940, 0.3099, 0.5566, 0.8055, 0.7375, 0.6576,
          0.2634, 0.3268],
         [0.0560, 0.1184, 0.8799, 0.2502, 0.0641, 0.4755, 0.6467, 0.5081,
          0.4761, 0.6961],
         [0.5255, 0.3520, 0.0834, 0.1742, 0.0405, 0.1918, 0.0987, 0.5202,
          0.0562, 0.9164],
         [0.2344, 0.7884, 0.6993, 0.9018, 0.1653, 0.3691, 0.9946, 0.0796,
          0.2848, 0.6918],
         [0.6778, 0.3924, 0.8850, 0.4008, 0.6008, 0.3353, 0.3845, 0.6759,
          0.2477, 0.3875]],

        [[0.5709, 0.2653, 0.9955, 0.3349, 0.8744, 0.3034, 0.7233, 0.4320,
          0.8352, 0.7567],
         [0.1254, 0.2250, 0.5413, 0.2601, 0.9215, 0.2809, 0.5176, 0.2984,
          0.4658, 0.1654],
         [0.0112, 0.2606, 0.6813, 0.0999, 0.8944, 0.7745, 0.6734, 0.5757,
          0.2450, 0.7291],
         [0.6668, 0.6869, 0.1753, 0.6395, 0.6347, 0.5536, 0.9873, 0.1085,
          0.056

In [14]:
y = torch.gather(y, 1, nbh)
y

tensor([[[0.3855, 0.2628, 0.1940,  ..., 0.6576, 0.2634, 0.3268],
         [0.0560, 0.1184, 0.8799,  ..., 0.5081, 0.4761, 0.6961],
         [0.5255, 0.3520, 0.0834,  ..., 0.5202, 0.0562, 0.9164],
         ...,
         [0.0560, 0.1184, 0.8799,  ..., 0.5081, 0.4761, 0.6961],
         [0.5255, 0.3520, 0.0834,  ..., 0.5202, 0.0562, 0.9164],
         [0.2344, 0.7884, 0.6993,  ..., 0.0796, 0.2848, 0.6918]],

        [[0.1254, 0.2250, 0.5413,  ..., 0.2984, 0.4658, 0.1654],
         [0.0112, 0.2606, 0.6813,  ..., 0.5757, 0.2450, 0.7291],
         [0.6668, 0.6869, 0.1753,  ..., 0.1085, 0.0560, 0.9428],
         ...,
         [0.0112, 0.2606, 0.6813,  ..., 0.5757, 0.2450, 0.7291],
         [0.6668, 0.6869, 0.1753,  ..., 0.1085, 0.0560, 0.9428],
         [0.9001, 0.7974, 0.7546,  ..., 0.4539, 0.1846, 0.8529]],

        [[0.9566, 0.6905, 0.2711,  ..., 0.9283, 0.4982, 0.4106],
         [0.0648, 0.4538, 0.8101,  ..., 0.2294, 0.6661, 0.8426],
         [0.0329, 0.1639, 0.2412,  ..., 0.4294, 0.3140, 0.

In [15]:

y.shape

torch.Size([4, 30, 10])

In [16]:
W.shape


NameError: name 'W' is not defined

In [18]:
y = y.view(nbh_shape[0], nbh_shape[1], nbh_shape[2], -1)


In [20]:
y.shape

torch.Size([4, 6, 5, 10])