## <span style="color:red">Batchwise structure optimization is deprecated and will be upgraded soon</span>


# Batch-wise Structure Relaxation

In this tutorial, we show how to use the ``ASEBatchwiseLBFGS``. It enables relaxation of structures in a batch-wise manner, i.e. it optimizes multiple structures in parallel. This is particularly useful, when many relatively similar structures (--> similar time until convergence) should be relaxed while requiring possibly short simulation time.

In [64]:
import os
import shutil

import torch
from ase.io import read

import schnetpack as spk
from schnetpack import properties
from schnetpack.interfaces.ase_interface import AtomsConverter, SpkCalculator
from schnetpack.interfaces.batchwise_optimization import ASEBatchwiseLBFGS, BatchwiseCalculator

from schnetpack.utils.compatibility import load_model

from schnetpack.datasets.rmd17 import rMD17

import numpy as np
from scipy.optimize import linear_sum_assignment

from copy import copy, deepcopy

from ase.optimize import LBFGS
from ase.build import minimize_rotation_and_translation

First, we load the force field model that provides the forces for the relaxation process. Furthermore, we define the atoms converter, which is used to convert ase Atoms objects to SchNetPack input. Eventually the calculator is initialized. The latter provides the necessary functionality to load a model and calculates forces and energy for the respective structures. Please note that running batchwise relaxations is significantly faster on a cuda device.

In [65]:
model_path = "../../tests/testdata/md_ethanol.model"

# set device
device = torch.device("cpu")

# load model
model = load_model(model_path, device=device)

# define neighbor list
cutoff = model.representation.cutoff.item()
nbh_list=spk.transform.MatScipyNeighborList(cutoff=cutoff)

# build atoms converter
atoms_converter = AtomsConverter(
    neighbor_list=nbh_list,
    device=device,
)

# build calculator
calculator = BatchwiseCalculator(
    model=model_path,
    atoms_converter=atoms_converter,
    device=device,
    energy_unit="kcal/mol",
    position_unit="Ang",
)

/home/jonas/Documents/schnetpack/src/schnetpack/utils/compatibility.py:41: UserWarning: Model was saved without version information. Conversion to current version may fail.
  warnings.warn(


Subsequently, we load the batch of initial structures utilizing ASE (supports xyz, db and more).

In [66]:
input_structure_file = "../../tests/testdata/ethanol_conformers.xyz"

# load a single initial structure
conformers = read(input_structure_file, index=":")

# create a batch of structures by adding random noise to the atomic positions
n_replica = 5
noise_std = 0.05  # standard deviation of the Gaussian noise in Angstrom

ats = []
for _ in range(n_replica):
    for single_atoms in conformers:
        noisy_atoms = single_atoms.copy()
        noisy_atoms.positions += np.random.normal(scale=noise_std, size=noisy_atoms.positions.shape)
        ats.append(noisy_atoms)

inputs = atoms_converter(copy(ats))

In [67]:
inputs

{'_n_atoms': tensor([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]),
 '_atomic_numbers': tensor([6, 6, 8, 1, 1, 1, 1, 1, 1, 6, 6, 8, 1, 1, 1, 1, 1, 1, 6, 6, 8, 1, 1, 1,
         1, 1, 1, 6, 6, 8, 1, 1, 1, 1, 1, 1, 6, 6, 8, 1, 1, 1, 1, 1, 1, 6, 6, 8,
         1, 1, 1, 1, 1, 1, 6, 6, 8, 1, 1, 1, 1, 1, 1, 6, 6, 8, 1, 1, 1, 1, 1, 1,
         6, 6, 8, 1, 1, 1, 1, 1, 1, 6, 6, 8, 1, 1, 1, 1, 1, 1, 6, 6, 8, 1, 1, 1,
         1, 1, 1, 6, 6, 8, 1, 1, 1, 1, 1, 1, 6, 6, 8, 1, 1, 1, 1, 1, 1, 6, 6, 8,
         1, 1, 1, 1, 1, 1, 6, 6, 8, 1, 1, 1, 1, 1, 1]),
 '_positions': tensor([[-2.9711e-02, -5.2859e-01, -1.4476e-01],
         [-1.1947e+00,  2.7561e-01,  2.8191e-02],
         [ 1.0797e+00,  3.1478e-01,  4.4195e-02],
         [ 5.6973e-03, -1.2998e+00,  9.0619e-01],
         [ 5.2082e-02, -1.2524e+00, -9.1580e-01],
         [-1.3819e+00,  8.1425e-01,  8.9888e-01],
         [-1.3220e+00,  7.9862e-01, -7.8661e-01],
         [-2.1865e+00, -3.6366e-01,  3.2513e-02],
         [ 1.8928e+00, -2.4956e-01, -6

For some systems it helps to fix the positions of certain atoms during the relaxation. This can be achieved by providing a mask of boolean entries to ``ASEBatchwiseLBFGS``. The mask is a list of $n_\text{atoms}$ entries, indicating atoms, which positions are fixed during the relaxation. Here, we do not fix any atoms. Hence, the mask only contains ``True``.

In [68]:
# define structure mask for optimization (True for fixed, False for non-fixed)
n_atoms = len(ats[0].get_atomic_numbers())
single_structure_mask = [False for _ in range(n_atoms)]
# expand mask by number of input structures (fixed atoms are equivalent for all input structures)
mask = single_structure_mask * len(ats)

Finally, we run the optimization:

In [69]:
results_dir = "./howto_batchwise_relaxations_outputs"
if not os.path.exists(results_dir):
    os.makedirs(results_dir)

# Initialize optimizer
optimizer = ASEBatchwiseLBFGS(
    calculator=calculator,
    inputs=inputs,
    trajectory="./howto_batchwise_relaxations_outputs/relax_traj",
    log_every_step=True,
)

# run optimization
optimizer.run(fmax=0.001, steps=1000)

/home/jonas/miniforge3/envs/schnetpack/lib/python3.13/site-packages/ase/optimize/optimize.py:92: FutureWarning: Log flushes by default now.  Please do not call flush().  If you want a different flushing behaviour please open logfile yourself and choose buffering mode as appropriate.  This flush() method currently does nothing.
  warnings.warn('Log flushes by default now.  Please do not call '


                   Step     Time         fmax
ASEBatchwiseLBFGS:    0 17:58:28      10.8399
ASEBatchwiseLBFGS:    1 17:58:28       4.9663
ASEBatchwiseLBFGS:    2 17:58:28       2.6165
ASEBatchwiseLBFGS:    3 17:58:28       2.8583
ASEBatchwiseLBFGS:    4 17:58:28       0.5908
ASEBatchwiseLBFGS:    5 17:58:28       0.2878
ASEBatchwiseLBFGS:    6 17:58:28       0.2517
ASEBatchwiseLBFGS:    7 17:58:28       0.2266
ASEBatchwiseLBFGS:    8 17:58:28       0.1879
ASEBatchwiseLBFGS:    9 17:58:28       0.1167
ASEBatchwiseLBFGS:   10 17:58:28       0.0972
ASEBatchwiseLBFGS:   11 17:58:29       0.0760
ASEBatchwiseLBFGS:   12 17:58:29       0.0696
ASEBatchwiseLBFGS:   13 17:58:29       0.0700
ASEBatchwiseLBFGS:   14 17:58:29       0.0416
ASEBatchwiseLBFGS:   15 17:58:29       0.0385
ASEBatchwiseLBFGS:   16 17:58:29       0.0335
ASEBatchwiseLBFGS:   17 17:58:29       0.0365
ASEBatchwiseLBFGS:   18 17:58:29       0.0441
ASEBatchwiseLBFGS:   19 17:58:29       0.0342
ASEBatchwiseLBFGS:   20 17:58:29  

tensor(True)

In [71]:
#from ase.visualize import view
#ats_relax = read("./howto_batchwise_relaxations_outputs/relax_traj_seq_9.xyz", index=":")
#view(ats_relax)

Optimzed structures (in the form of ASE `Atoms`) and properties can be obtained with the `get_relaxation_results` function.

In [72]:
# get list of optimized structures and properties
opt_atoms, opt_props = optimizer.get_relaxation_results()

for oatoms in opt_atoms:
    print(oatoms.get_positions())
    
print(opt_props)

[[-1.56100644e-02 -6.01408064e-01 -7.13211531e-03]
 [-1.28614926e+00  2.27867559e-01  1.96272600e-02]
 [ 1.10196507e+00  3.01619709e-01  1.56054460e-02]
 [ 1.50911240e-02 -1.27921915e+00  8.67160201e-01]
 [ 1.05136978e-02 -1.22851288e+00 -9.18631494e-01]
 [-1.32535148e+00  8.45729887e-01  9.27852213e-01]
 [-1.33068740e+00  8.95379663e-01 -8.52516413e-01]
 [-2.17085600e+00 -4.24284488e-01  4.09580255e-03]
 [ 1.91652536e+00 -2.27932483e-01  2.05009070e-04]]
[[ 0.00256606 -0.69933635 -0.05594113]
 [-1.17466486  0.26381847  0.04196055]
 [ 1.26071012 -0.03850747 -0.25296235]
 [ 0.04027582 -1.35198689  0.83709466]
 [-0.11092263 -1.35523188 -0.93203056]
 [-1.08862615  0.91221744  0.9283877 ]
 [-1.22603667  0.90555203 -0.84887832]
 [-2.1221056  -0.28948325  0.12859666]
 [ 1.41544938  0.53855079  0.515526  ]]
[[-0.002196   -0.70274472  0.07524479]
 [-1.16570449  0.27841485 -0.00670195]
 [ 1.26666629 -0.06233515  0.27099445]
 [-0.1203188  -1.36501694  0.94589758]
 [ 0.02081957 -1.34744406 -0.824

In [73]:
# build calculator
calculator = SpkCalculator(
    model_file=model_path,
    neighbor_list=nbh_list,
    device=device,
    energy_unit="kcal/mol",
    position_unit="Ang",
)

INFO:schnetpack.interfaces.ase_interface:Loading model from ../../tests/testdata/md_ethanol.model


In [74]:
# relax every structure on its own, starting from the same initial geometries.
# deepcopy is required here, since LBFGS relaxes the Atoms objects in place.
seq_atoms = []
for at_idx, at in enumerate(deepcopy(ats)):

    at.calc = calculator
    lbfgs = LBFGS(at, trajectory=f"./howto_batchwise_relaxations_outputs/relax_traj_seq_{at_idx}.xyz")
    lbfgs.run(fmax=0.001)

    seq_atoms.append(at)

       Step     Time          Energy          fmax
LBFGS:    0 18:01:58    -4214.025370        6.632635
LBFGS:    1 18:01:58    -4215.166049        3.259666
LBFGS:    2 18:01:58    -4215.320195        1.439660
LBFGS:    3 18:01:58    -4215.364237        0.474534
LBFGS:    4 18:01:58    -4215.384225        0.397689
LBFGS:    5 18:01:58    -4215.397438        0.210220
LBFGS:    6 18:01:58    -4215.399470        0.142528
LBFGS:    7 18:01:58    -4215.400825        0.124511
LBFGS:    8 18:01:58    -4215.401842        0.129559
LBFGS:    9 18:01:58    -4215.402181        0.063929
LBFGS:   10 18:01:58    -4215.402519        0.032760
LBFGS:   11 18:01:58    -4215.402519        0.032649
LBFGS:   12 18:01:58    -4215.402858        0.031613
LBFGS:   13 18:01:58    -4215.402858        0.017598
LBFGS:   14 18:01:58    -4215.402858        0.012891
LBFGS:   15 18:01:58    -4215.402858        0.009445
LBFGS:   16 18:01:58    -4215.402858        0.010501
LBFGS:   17 18:01:58    -4215.402858        0.00

## Comparing batch-wise and sequential relaxation

* **RMSD** between the two relaxed geometries
* **Potential energy**, evaluated for both sets of structures with the *same* `SpkCalculator`

Two effects make a plain RMSD misleading. A relaxation may translate and rotate the molecule as a whole -- removed with ASE's `minimize_rotation_and_translation`. And identical atoms are indistinguishable: ethanol's CH$_3$ group rotates freely, so a 120° methyl rotation returns the same physical structure with the three hydrogens relabelled. Pairing atoms by index would report a large deviation for two structures that are in fact identical.

We therefore also report a **permutation-matched RMSD**, minimised over rigid-body motion *and* relabellings of like atoms (Hungarian assignment via `scipy.optimize.linear_sum_assignment`, alternated with the superposition until the assignment stops changing).

In [75]:
def rmsd(P, Q):
    return np.sqrt(((P - Q) ** 2).sum() / len(P))


def matched_rmsd(atoms, reference, max_iter=20):
    """RMSD minimized over rigid-body motion *and* relabellings of atoms with identical type.

    Alternates the Kabsch superposition with an optimal assignment of identical
    elements until the permutation stops changing. Returns (rmsd, permutation),
    where permutation[i] is the atom of `atoms` matched to atom i of `reference`.
    """
    ref_pos = reference.get_positions()
    symbols = np.array(reference.get_chemical_symbols())
    groups = [np.where(symbols == s)[0] for s in sorted(set(symbols))]

    perm = np.arange(len(atoms))
    for _ in range(max_iter):
        current = atoms.copy()
        current.positions = atoms.get_positions()[perm]
        minimize_rotation_and_translation(reference, current)
        pos = current.get_positions()

        new_perm = perm.copy()
        for idx in groups:
            cost = ((pos[idx][:, None, :] - ref_pos[None, idx, :]) ** 2).sum(-1)
            row, col = linear_sum_assignment(cost)
            new_perm[idx[col]] = perm[idx[row]]

        if np.array_equal(new_perm, perm):
            return rmsd(pos, ref_pos), perm
        perm = new_perm

    raise RuntimeError("permutation did not converge")


def evaluate(atoms_list):
    """Energies and maximum force components, all from the same SpkCalculator."""
    energies, fmax = [], []
    for a in atoms_list:
        a = a.copy()
        a.calc = calculator
        energies.append(a.get_potential_energy())
        fmax.append(np.abs(a.get_forces()).max())
    return np.array(energies), np.array(fmax)


e_batch, fmax_batch = evaluate(opt_atoms)
e_seq, fmax_seq = evaluate(seq_atoms)

rmsd_raw = np.array([rmsd(b.positions, s.positions) for b, s in zip(opt_atoms, seq_atoms)])
rmsd_matched = np.array([matched_rmsd(b, s)[0] for b, s in zip(opt_atoms, seq_atoms)])

header = (
    f"{'i':>2} {'RMSD raw':>10} {'RMSD matched':>13} "
    f"{'E_batch [eV]':>14} {'E_seq [eV]':>14} {'dE [meV]':>10}"
)
print(header)
print("-" * len(header))
for i in range(len(opt_atoms)):
    print(
        f"{i:>2} {rmsd_raw[i]:>10.2e} {rmsd_matched[i]:>13.2e} "
        f"{e_batch[i]:>14.6f} {e_seq[i]:>14.6f} {(e_batch[i] - e_seq[i]) * 1e3:>10.2e}"
    )

dE = e_batch - e_seq
print()
print(f"RMSD matched : mean {rmsd_matched.mean():.2e} A, max {rmsd_matched.max():.2e} A")
print(f"RMSD raw     : mean {rmsd_raw.mean():.2e} A, max {rmsd_raw.max():.2e} A")
print(f"dE           : mean {dE.mean() * 1e3:.2e} meV, max|dE| {np.abs(dE).max() * 1e3:.2e} meV")
print(f"energy spread within batch-wise results : {(e_batch.max() - e_batch.min()) * 1e3:.2e} meV")
print(f"energy spread within sequential results : {(e_seq.max() - e_seq.min()) * 1e3:.2e} meV")
print(f"max force component: batch-wise {fmax_batch.max():.2e}, sequential {fmax_seq.max():.2e} eV/A")

 i   RMSD raw  RMSD matched   E_batch [eV]     E_seq [eV]   dE [meV]
--------------------------------------------------------------------
 0   2.31e-06      1.55e-06   -4215.402858   -4215.402858   0.00e+00
 1   1.36e-06      1.87e-07   -4215.405568   -4215.405568   0.00e+00
 2   3.89e-05      3.89e-05   -4215.405568   -4215.405568   0.00e+00
 3   1.70e-06      4.55e-07   -4215.402858   -4215.402858   0.00e+00
 4   1.37e-06      4.12e-07   -4215.405568   -4215.405568   0.00e+00
 5   1.69e-06      5.36e-07   -4215.405568   -4215.405568   0.00e+00
 6   1.08e-06      4.07e-07   -4215.402858   -4215.402858   0.00e+00
 7   9.47e-07      3.09e-07   -4215.405568   -4215.405568   0.00e+00
 8   1.41e-06      4.63e-07   -4215.405568   -4215.405568   0.00e+00
 9   1.37e-06      5.25e-07   -4215.402858   -4215.402858   0.00e+00
10   3.77e-05      3.76e-05   -4215.405568   -4215.405568   0.00e+00
11   2.24e-06      1.27e-06   -4215.405568   -4215.405568   0.00e+00
12   1.51e-06      2.36e-07   -421

Sanity check of RMSD matched

In [76]:
reference = seq_atoms[0]
print("atom order:", reference.get_chemical_symbols())

# atoms 2, 3, 4 are the methyl hydrogens (all bonded to C0); relabel them cyclically
relabelled = reference.copy()
relabelled.positions = reference.get_positions()[[0, 1, 3, 4, 2, 5, 6, 7, 8]]

e_ref, e_relabelled = evaluate([reference, relabelled])[0]
r, perm = matched_rmsd(relabelled, reference)

print(f"energy difference        : {(e_relabelled - e_ref) * 1e3:.2e} meV")
print(f"RMSD matched             : {r:.2e} A")
print(f"recovered permutation    : {perm}")

atom order: ['C', 'C', 'O', 'H', 'H', 'H', 'H', 'H', 'H']
energy difference        : 3.62e+03 meV
RMSD matched             : 9.64e-01 A
recovered permutation    : [0 1 2 3 4 5 6 7 8]


In [77]:
if os.path.exists(results_dir):
    shutil.rmtree(results_dir)